baseURL = "https://xsymphony.github.io/"
languageCode = "zh-CH"
title = "Matrix"
theme = "maupassant-hugo"

preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
summaryLength = 140

[author]
    name = "matrix"

[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

[params]
    author = "matrix"
    keywords = "golang,python"

    [params.utteranc]
        enable = true
        repo = "xsymphony/comments"
        issueTerm = "pathname"
        theme = "github-light"

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4